version: '3.4'

services:

  mysql:
    image: ${DTR_URL}/alex/mysql-jps
    ports:
      - target: 3306
        published: 3306
    deploy:
      placement:
        constraints:
        - node.labels.database == mysql
    networks:
    - jps-net
    volumes:
      - type: volume
        mysqldata: /var/lib/mysql
        # volume:
        #   nocopy: true

networks:
  jps-net:

volumes:
  mysqldata:
    external: true
    name: mysqldata