version: '3.4'

services:

  mysql:
    image: ${DTR_URL}/alex/mysql-jps
    environment:
      # it's assumed that variables are defined in jenkins project 
      # and corresponding secrets exist in orchestration environment
      MYSQL_ROOT_PASSWORD_FILE=/run/secrets/${DB_ROOT_PASSWORD_SECRET}
      MYSQL_PASSWORD_FILE=/run/secrets/${DB_PASSWORD_SECRET}
      MYSQL_USER_FILE=/run/secrets/${DB_USER_SECRET}
    ports:
      - target: 3306
        published: 3306
    deploy:
      placement:
        constraints:
        - node.labels.database == mysql
    networks:
    - jps-net
    volumes:
      - type: volume
        source: mysqldata
        target: /var/lib/mysql
      # - mysqldata: /var/lib/mysql
        # volume:
        #   nocopy: true

networks:
  jps-net:

volumes:
  mysqldata:
    external: true
    name: mysqldata