version: '3.4'

services:

  mysql:
    image: ${DTR_URL}/alex/mysql-jps
    environment:
      # it's assumed that variables are defined in jenkins project 
      # and corresponding secrets exist in orchestration environment
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/${DB_ROOT_PASSWORD_SECRET}
        MYSQL_PASSWORD_FILE=/run/secrets/${DB_PASSWORD_SECRET}
        MYSQL_USER_FILE=/run/secrets/${DB_USER_SECRET}
    ports:
      - target: 3306
        published: 3306
    deploy:
      placement:
        constraints:
        - node.labels.database == mysql
    secrets:
      - mysql_root_password
      - mysql_user
      - mysql_password
    networks:
    - jps-net
    volumes:
      - type: volume
        source: mysqldata
        target: /var/lib/mysql
      # - mysqldata: /var/lib/mysql
        # volume:
        #   nocopy: true

  webapp:
    image: ${DTR_URL}/alex/jps
    environment:
    # it's assumed that variables are defined in jenkins project 
    # and corresponding secrets exist in orchestration environment
    - DB_HOST=mysql
    # must use $$ to escape command in compose file
    - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - target: 8080
        published: 8000
    # deploy:
    #   placement:
    #     constraints:
    #     - node.labels.database == mysql
    secrets:
      - mysql_root_password
    networks:
    - jps-net

secrets:
  mysql_root_password:
    external: true
  mysql_user:
    external: true
  mysql_password:
    external: true

networks:
  jps-net:
    # driver: overlay

volumes:
  mysqldata:
    external: true
    name: mysqldata